### ISSUE TITLE
Can't run develop after latest update (2.3.5) releashed

### ISSUE THREAD

**Issue by GoldenCoffee** [ComfortablyCoding/strapi-plugin-slugify#112]
Hi,
I've provided some informations to see if that helps:

- My Yarn Version: 1.22.19
- Strapi Version: 4.13.7
- Node Version: v18.18.0
- Database: mysql (v8)

Here's some error report from console:
```
E:\Others\strapi\tutorial-strapi-with-nextjs> yarn develop
yarn run v1.22.19
$ strapi develop
Error: Could not load js config file E:\Others\strapi\tutorial-strapi-with-nextjs\node_modules\strapi-plugin-slugify\strapi-server.js: Cannot find module '@strapi/strapi/dist/core-api/controller/transform'
Require stack:
- E:\Others\strapi\tutorial-strapi-with-nextjs\node_modules\strapi-plugin-slugify\server\controllers\slug-controller.js
- E:\Others\strapi\tutorial-strapi-with-nextjs\node_modules\strapi-plugin-slugify\server\controllers\index.js
- E:\Others\strapi\tutorial-strapi-with-nextjs\node_modules\strapi-plugin-slugify\server\index.js
- E:\Others\strapi\tutorial-strapi-with-nextjs\node_modules\strapi-plugin-slugify\strapi-server.js
- E:\Others\strapi\tutorial-strapi-with-nextjs\node_modules\@strapi\utils\dist\import-default.js
- E:\Others\strapi\tutorial-strapi-with-nextjs\node_modules\@strapi\utils\dist\index.js
- E:\Others\strapi\tutorial-strapi-with-nextjs\node_modules\@strapi\strapi\lib\services\entity-service\components.js
- E:\Others\strapi\tutorial-strapi-with-nextjs\node_modules\@strapi\data-transfer\dist\strapi\queries\entity.js
- E:\Others\strapi\tutorial-strapi-with-nextjs\node_modules\@strapi\data-transfer\dist\strapi\queries\index.js
- E:\Others\strapi\tutorial-strapi-with-nextjs\node_modules\@strapi\data-transfer\dist\strapi\providers\local-destination\strategies\restore\index.js
- E:\Others\strapi\tutorial-strapi-with-nextjs\node_modules\@strapi\data-transfer\dist\strapi\providers\local-destination\strategies\index.js
- E:\Others\strapi\tutorial-strapi-with-nextjs\node_modules\@strapi\data-transfer\dist\strapi\providers\local-destination\index.js
- E:\Others\strapi\tutorial-strapi-with-nextjs\node_modules\@strapi\data-transfer\dist\strapi\providers\index.js
- E:\Others\strapi\tutorial-strapi-with-nextjs\node_modules\@strapi\data-transfer\dist\strapi\index.js
- E:\Others\strapi\tutorial-strapi-with-nextjs\node_modules\@strapi\data-transfer\dist\index.js
- E:\Others\strapi\tutorial-strapi-with-nextjs\node_modules\@strapi\strapi\lib\commands\utils\data-transfer.js
- E:\Others\strapi\tutorial-strapi-with-nextjs\node_modules\@strapi\strapi\lib\commands\actions\export\command.js
- E:\Others\strapi\tutorial-strapi-with-nextjs\node_modules\@strapi\strapi\lib\commands\index.js
- E:\Others\strapi\tutorial-strapi-with-nextjs\node_modules\@strapi\strapi\bin\strapi.js
    at loadJsFile (E:\Others\strapi\tutorial-strapi-with-nextjs\node_modules\@strapi\strapi\lib\core\app-configuration\load-config-file.js:18:11)
    at loadFile (E:\Others\strapi\tutorial-strapi-with-nextjs\node_modules\@strapi\strapi\lib\core\app-configuration\load-config-file.js:35:14)
    at Object.loadPlugins (E:\Others\strapi\tutorial-strapi-with-nextjs\node_modules\@strapi\strapi\lib\core\loaders\plugins\index.js:103:26)
    at async Strapi.loadPlugins (E:\Others\strapi\tutorial-strapi-with-nextjs\node_modules\@strapi\strapi\lib\Strapi.js:352:5)
    at async Promise.all (index 3)
    at async Strapi.register (E:\Others\strapi\tutorial-strapi-with-nextjs\node_modules\@strapi\strapi\lib\Strapi.js:392:5)
    at async Strapi.load (E:\Others\strapi\tutorial-strapi-with-nextjs\node_modules\@strapi\strapi\lib\Strapi.js:503:5)
    at async workerProcess (E:\Others\strapi\tutorial-strapi-with-nextjs\node_modules\@strapi\strapi\lib\commands\actions\develop\action.js:110:26)
```

<hr />

And that's not all. I just saw our dev update to the latest version, but before that, **my Strapi can't run slugify 2.3.4 as well either.**
So let's see what happened last night:
I set up roles and tested json and they all working good, but when i enable slugify and try to get json, it throw the error:

```
    data: null,
    error: {
      status: 400,
      name: 'ValidationError',
      message: 'film model name not found, all models must be defined in the settings and are case sensitive.',
      details: {}
    }
```

I immediately checked this error from github and it seemed to come from a long time ago: This error seem the same as #75. 

I also get lots of warning print in my console:
```
PS E:\Others\strapi\tutorial-strapi-with-nextjs> yarn add strapi-plugin-slugify@1.1.0
yarn add v1.22.19
[1/5] Validating package.json...
[2/5] Resolving packages...
Couldn't find any versions for "strapi-plugin-slugify" that matches "1.1.0"
? Please choose a version of "strapi-plugin-slugify" from this list: 2.3.4
[3/5] Fetching packages...
[4/5] Linking dependencies...
warning " > @strapi/plugin-i18n@4.13.7" has unmet peer dependency "react@^17.0.0 || ^18.0.0".
warning " > @strapi/plugin-i18n@4.13.7" has unmet peer dependency "react-dom@^17.0.0 || ^18.0.0".
warning " > @strapi/plugin-i18n@4.13.7" has unmet peer dependency "react-router-dom@5.3.4".
warning " > @strapi/plugin-i18n@4.13.7" has unmet peer dependency "styled-components@5.3.3".
warning "@strapi/plugin-i18n > @strapi/design-system@1.10.1" has unmet peer dependency "react@^17.0.0 || ^18.0.0".
warning "@strapi/plugin-i18n > @strapi/design-system@1.10.1" has unmet peer dependency "react-dom@^17.0.0 || ^18.0.0".
warning "@strapi/plugin-i18n > @strapi/design-system@1.10.1" has unmet peer dependency "react-router-dom@^5.2.0".
warning "@strapi/plugin-i18n > @strapi/design-system@1.10.1" has unmet peer dependency "styled-components@^5.2.1".
warning "@strapi/plugin-i18n > @strapi/helper-plugin@4.13.7" has unmet peer dependency "react@^17.0.0 || ^18.0.0".
warning "@strapi/plugin-i18n > @strapi/helper-plugin@4.13.7" has unmet peer dependency "react-dom@^17.0.0 || ^18.0.0".
warning "@strapi/plugin-i18n > @strapi/helper-plugin@4.13.7" has unmet peer dependency "react-router-dom@^5.3.4".
warning "@strapi/plugin-i18n > @strapi/helper-plugin@4.13.7" has unmet peer dependency "styled-components@^5.3.3".
warning "@strapi/plugin-i18n > @strapi/icons@1.10.1" has unmet peer dependency "react@^17.0.0 || ^18.0.0".
warning "@strapi/plugin-i18n > @strapi/icons@1.10.1" has unmet peer dependency "react-dom@^17.0.0 || ^18.0.0".
warning "@strapi/plugin-i18n > formik@2.4.0" has unmet peer dependency "react@>=16.8.0".
warning "@strapi/plugin-i18n > react-intl@6.4.1" has unmet peer dependency "react@^16.6.0 || 17 || 18".
warning "@strapi/plugin-i18n > react-query@3.39.3" has unmet peer dependency "react@^16.8.0 || ^17.0.0 || ^18.0.0".
warning "@strapi/plugin-i18n > react-redux@8.1.1" has unmet peer dependency "react@^16.8 || ^17.0 || ^18.0".
warning "@strapi/plugin-i18n > @strapi/design-system > @floating-ui/react-dom@2.0.2" has unmet peer dependency "react@>=16.8.0".
warning "@strapi/plugin-i18n > @strapi/design-system > @floating-ui/react-dom@2.0.2" has unmet peer dependency "react-dom@>=16.8.0".
warning "@strapi/plugin-i18n > @strapi/design-system > @radix-ui/react-dismissable-layer@1.0.5" has unmet peer dependency "react@^16.8 || ^17.0 || ^18.0".
warning "@strapi/plugin-i18n > @strapi/design-system > @radix-ui/react-dismissable-layer@1.0.5" has unmet peer dependency "react-dom@^16.8 || ^17.0 || ^18.0".
warning "@strapi/plugin-i18n > @strapi/design-system > @radix-ui/react-dropdown-menu@2.0.6" has unmet peer dependency "react@^16.8 || ^17.0 || ^18.0".
warning "@strapi/plugin-i18n > @strapi/design-system > @radix-ui/react-dropdown-menu@2.0.6" has unmet peer dependency "react-dom@^16.8 || ^17.0 || ^18.0".
warning "@strapi/plugin-i18n > @strapi/design-system > @radix-ui/react-focus-scope@1.0.3" has unmet peer dependency "react@^16.8 || ^17.0 || ^18.0".
warning "@strapi/plugin-i18n > @strapi/design-system > @radix-ui/react-focus-scope@1.0.3" has unmet peer dependency "react-dom@^16.8 || ^17.0 || ^18.0".
warning "@strapi/plugin-i18n > @strapi/design-system > @strapi/ui-primitives@1.11.0" has unmet peer dependency "react@^17.0.0 || ^18.0.0".
warning "@strapi/plugin-i18n > @strapi/design-system > @strapi/ui-primitives@1.11.0" has unmet peer dependency "react-dom@^17.0.0 || ^18.0.0".
warning "@strapi/plugin-i18n > @strapi/design-system > @uiw/react-codemirror@4.21.18" has unmet peer dependency "@babel/runtime@>=7.11.0".
warning "@strapi/plugin-i18n > @strapi/design-system > @uiw/react-codemirror@4.21.18" has unmet peer dependency "@codemirror/state@>=6.0.0".
warning "@strapi/plugin-i18n > @strapi/design-system > @uiw/react-codemirror@4.21.18" has unmet peer dependency "@codemirror/theme-one-dark@>=6.0.0".
warning "@strapi/plugin-i18n > @strapi/design-system > @uiw/react-codemirror@4.21.18" has unmet peer dependency "@codemirror/view@>=6.0.0".
warning "@strapi/plugin-i18n > @strapi/design-system > @uiw/react-codemirror@4.21.18" has unmet peer dependency "codemirror@>=6.0.0".
warning "@strapi/plugin-i18n > @strapi/design-system > @uiw/react-codemirror@4.21.18" has unmet peer dependency "react@>=16.8.0".
warning "@strapi/plugin-i18n > @strapi/design-system > @uiw/react-codemirror@4.21.18" has unmet peer dependency "react-dom@>=16.8.0".
warning "@strapi/plugin-i18n > @strapi/design-system > react-remove-scroll@2.5.6" has unmet peer dependency "react@^16.8.0 || ^17.0.0 || ^18.0.0".
warning "@strapi/plugin-i18n > @strapi/helper-plugin > react-helmet@6.1.0" has unmet peer dependency "react@>=16.3.0".
warning "@strapi/plugin-i18n > @strapi/helper-plugin > react-select@5.7.0" has unmet peer dependency "react@^16.8.0 || ^17.0.0 || ^18.0.0".
warning "@strapi/plugin-i18n > @strapi/helper-plugin > react-select@5.7.0" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0 || ^18.0.0".
warning "@strapi/plugin-i18n > react-redux > use-sync-external-store@1.2.0" has unmet peer dependency "react@^16.8.0 || ^17.0.0 || ^18.0.0".
warning "@strapi/plugin-i18n > @strapi/design-system > @radix-ui/react-dismissable-layer > @radix-ui/react-compose-refs@1.0.1" has unmet peer dependency "react@^16.8 || ^17.0 || ^18.0".
warning "@strapi/plugin-i18n > @strapi/design-system > @radix-ui/react-dismissable-layer > @radix-ui/react-primitive@1.0.3" has unmet peer dependency "react@^16.8 || ^17.0 || ^18.0".
warning "@strapi/plugin-i18n > @strapi/design-system > @radix-ui/react-dismissable-layer > @radix-ui/react-primitive@1.0.3" has unmet peer dependency "react-dom@^16.8 || ^17.0 || ^18.0".        
warning "@strapi/plugin-i18n > @strapi/design-system > @radix-ui/react-dismissable-layer > @radix-ui/react-use-callback-ref@1.0.1" has unmet peer dependency "react@^16.8 || ^17.0 || ^18.0".     
warning "@strapi/plugin-i18n > @strapi/design-system > @radix-ui/react-dismissable-layer > @radix-ui/react-use-escape-keydown@1.0.3" has unmet peer dependency "react@^16.8 || ^17.0 || ^18.0".   
warning "@strapi/plugin-i18n > @strapi/design-system > @radix-ui/react-dropdown-menu > @radix-ui/react-context@1.0.1" has unmet peer dependency "react@^16.8 || ^17.0 || ^18.0".
warning "@strapi/plugin-i18n > @strapi/design-system > @radix-ui/react-dropdown-menu > @radix-ui/react-id@1.0.1" has unmet peer dependency "react@^16.8 || ^17.0 || ^18.0".
warning "@strapi/plugin-i18n > @strapi/design-system > @radix-ui/react-dropdown-menu > @radix-ui/react-menu@2.0.6" has unmet peer dependency "react@^16.8 || ^17.0 || ^18.0".
warning "@strapi/plugin-i18n > @strapi/design-system > @radix-ui/react-dropdown-menu > @radix-ui/react-menu@2.0.6" has unmet peer dependency "react-dom@^16.8 || ^17.0 || ^18.0".
warning "@strapi/plugin-i18n > @strapi/design-system > @radix-ui/react-dropdown-menu > @radix-ui/react-use-controllable-state@1.0.1" has unmet peer dependency "react@^16.8 || ^17.0 || ^18.0".   
warning "@strapi/plugin-i18n > @strapi/design-system > @strapi/ui-primitives > @radix-ui/react-collection@1.0.3" has unmet peer dependency "react@^16.8 || ^17.0 || ^18.0".
warning "@strapi/plugin-i18n > @strapi/design-system > @strapi/ui-primitives > @radix-ui/react-collection@1.0.3" has unmet peer dependency "react-dom@^16.8 || ^17.0 || ^18.0".
warning "@strapi/plugin-i18n > @strapi/design-system > @strapi/ui-primitives > @radix-ui/react-direction@1.0.1" has unmet peer dependency "react@^16.8 || ^17.0 || ^18.0".
warning "@strapi/plugin-i18n > @strapi/design-system > @strapi/ui-primitives > @radix-ui/react-focus-guards@1.0.1" has unmet peer dependency "react@^16.8 || ^17.0 || ^18.0".
warning "@strapi/plugin-i18n > @strapi/design-system > @strapi/ui-primitives > @radix-ui/react-popper@1.1.3" has unmet peer dependency "react@^16.8 || ^17.0 || ^18.0".
warning "@strapi/plugin-i18n > @strapi/design-system > @strapi/ui-primitives > @radix-ui/react-popper@1.1.3" has unmet peer dependency "react-dom@^16.8 || ^17.0 || ^18.0".
warning "@strapi/plugin-i18n > @strapi/design-system > @strapi/ui-primitives > @radix-ui/react-portal@1.0.4" has unmet peer dependency "react@^16.8 || ^17.0 || ^18.0".
warning "@strapi/plugin-i18n > @strapi/design-system > @strapi/ui-primitives > @radix-ui/react-portal@1.0.4" has unmet peer dependency "react-dom@^16.8 || ^17.0 || ^18.0".
warning "@strapi/plugin-i18n > @strapi/design-system > @strapi/ui-primitives > @radix-ui/react-slot@1.0.2" has unmet peer dependency "react@^16.8 || ^17.0 || ^18.0".
warning "@strapi/plugin-i18n > @strapi/design-system > @strapi/ui-primitives > @radix-ui/react-use-layout-effect@1.0.1" has unmet peer dependency "react@^16.8 || ^17.0 || ^18.0".
warning "@strapi/plugin-i18n > @strapi/design-system > @strapi/ui-primitives > @radix-ui/react-use-previous@1.0.1" has unmet peer dependency "react@^16.8 || ^17.0 || ^18.0".
warning "@strapi/plugin-i18n > @strapi/design-system > @strapi/ui-primitives > @radix-ui/react-visually-hidden@1.0.3" has unmet peer dependency "react@^16.8 || ^17.0 || ^18.0".
warning "@strapi/plugin-i18n > @strapi/design-system > @strapi/ui-primitives > @radix-ui/react-visually-hidden@1.0.3" has unmet peer dependency "react-dom@^16.8 || ^17.0 || ^18.0".
warning "@strapi/plugin-i18n > @strapi/design-system > @uiw/react-codemirror > @uiw/codemirror-extensions-basic-setup@4.21.18" has unmet peer dependency "@codemirror/autocomplete@>=6.0.0".      
warning "@strapi/plugin-i18n > @strapi/design-system > @uiw/react-codemirror > @uiw/codemirror-extensions-basic-setup@4.21.18" has unmet peer dependency "@codemirror/language@>=6.0.0".
warning "@strapi/plugin-i18n > @strapi/design-system > @uiw/react-codemirror > @uiw/codemirror-extensions-basic-setup@4.21.18" has unmet peer dependency "@codemirror/lint@>=6.0.0".
warning "@strapi/plugin-i18n > @strapi/design-system > @uiw/react-codemirror > @uiw/codemirror-extensions-basic-setup@4.21.18" has unmet peer dependency "@codemirror/search@>=6.0.0".
warning "@strapi/plugin-i18n > @strapi/design-system > @uiw/react-codemirror > @uiw/codemirror-extensions-basic-setup@4.21.18" has unmet peer dependency "@codemirror/view@>=6.0.0".
warning "@strapi/plugin-i18n > @strapi/design-system > react-remove-scroll > react-remove-scroll-bar@2.3.4" has unmet peer dependency "react@^16.8.0 || ^17.0.0 || ^18.0.0".
warning "@strapi/plugin-i18n > @strapi/design-system > react-remove-scroll > react-style-singleton@2.2.1" has unmet peer dependency "react@^16.8.0 || ^17.0.0 || ^18.0.0".
warning "@strapi/plugin-i18n > @strapi/design-system > react-remove-scroll > use-callback-ref@1.3.0" has unmet peer dependency "react@^16.8.0 || ^17.0.0 || ^18.0.0".
warning "@strapi/plugin-i18n > @strapi/design-system > react-remove-scroll > use-sidecar@1.1.2" has unmet peer dependency "react@^16.8.0 || ^17.0.0 || ^18.0.0".
warning "@strapi/plugin-i18n > @strapi/helper-plugin > react-helmet > react-side-effect@2.1.2" has unmet peer dependency "react@^16.3.0 || ^17.0.0 || ^18.0.0".
warning "@strapi/plugin-i18n > @strapi/helper-plugin > react-select > @emotion/react@11.11.1" has unmet peer dependency "react@>=16.8.0".
warning "@strapi/plugin-i18n > @strapi/helper-plugin > react-select > react-transition-group@4.4.5" has unmet peer dependency "react@>=16.6.0".
warning "@strapi/plugin-i18n > @strapi/helper-plugin > react-select > react-transition-group@4.4.5" has unmet peer dependency "react-dom@>=16.6.0".
warning "@strapi/plugin-i18n > @strapi/helper-plugin > react-select > use-isomorphic-layout-effect@1.1.2" has unmet peer dependency "react@^16.8.0 || ^17.0.0 || ^18.0.0".
warning "@strapi/plugin-i18n > @strapi/design-system > @radix-ui/react-dropdown-menu > @radix-ui/react-menu > @radix-ui/react-focus-scope@1.0.4" has unmet peer dependency "react@^16.8 || ^17.0 || ^18.0".
warning "@strapi/plugin-i18n > @strapi/design-system > @radix-ui/react-dropdown-menu > @radix-ui/react-menu > @radix-ui/react-focus-scope@1.0.4" has unmet peer dependency "react-dom@^16.8 || ^17.0 || ^18.0".
warning "@strapi/plugin-i18n > @strapi/design-system > @radix-ui/react-dropdown-menu > @radix-ui/react-menu > @radix-ui/react-presence@1.0.1" has unmet peer dependency "react@^16.8 || ^17.0 || ^18.0".
warning "@strapi/plugin-i18n > @strapi/design-system > @radix-ui/react-dropdown-menu > @radix-ui/react-menu > @radix-ui/react-presence@1.0.1" has unmet peer dependency "react-dom@^16.8 || ^17.0 
|| ^18.0".
warning "@strapi/plugin-i18n > @strapi/design-system > @radix-ui/react-dropdown-menu > @radix-ui/react-menu > @radix-ui/react-roving-focus@1.0.4" has unmet peer dependency "react@^16.8 || ^17.0 
|| ^18.0".
warning "@strapi/plugin-i18n > @strapi/design-system > @radix-ui/react-dropdown-menu > @radix-ui/react-menu > @radix-ui/react-roving-focus@1.0.4" has unmet peer dependency "react-dom@^16.8 || ^17.0 || ^18.0".
warning "@strapi/plugin-i18n > @strapi/design-system > @radix-ui/react-dropdown-menu > @radix-ui/react-menu > react-remove-scroll@2.5.5" has unmet peer dependency "react@^16.8.0 || ^17.0.0 || ^18.0.0".
warning "@strapi/plugin-i18n > @strapi/design-system > @strapi/ui-primitives > @radix-ui/react-popper > @radix-ui/react-arrow@1.0.3" has unmet peer dependency "react@^16.8 || ^17.0 || ^18.0".   
warning "@strapi/plugin-i18n > @strapi/design-system > @strapi/ui-primitives > @radix-ui/react-popper > @radix-ui/react-arrow@1.0.3" has unmet peer dependency "react-dom@^16.8 || ^17.0 || ^18.0".
warning "@strapi/plugin-i18n > @strapi/design-system > @strapi/ui-primitives > @radix-ui/react-popper > @radix-ui/react-use-rect@1.0.1" has unmet peer dependency "react@^16.8 || ^17.0 || ^18.0".warning "@strapi/plugin-i18n > @strapi/design-system > @strapi/ui-primitives > @radix-ui/react-popper > @radix-ui/react-use-size@1.0.1" has unmet peer dependency "react@^16.8 || ^17.0 || ^18.0".warning "@strapi/plugin-i18n > @strapi/design-system > @uiw/react-codemirror > @uiw/codemirror-extensions-basic-setup > @codemirror/autocomplete@6.9.1" has unmet peer dependency "@lezer/common@^1.0.0".
warning "@strapi/plugin-i18n > @strapi/helper-plugin > react-select > @emotion/react > @emotion/use-insertion-effect-with-fallbacks@1.0.1" has unmet peer dependency "react@>=16.8.0".
warning " > @strapi/plugin-users-permissions@4.13.7" has unmet peer dependency "react@^17.0.0 || ^18.0.0".
warning " > @strapi/plugin-users-permissions@4.13.7" has unmet peer dependency "react-dom@^17.0.0 || ^18.0.0".
warning " > @strapi/plugin-users-permissions@4.13.7" has unmet peer dependency "react-router-dom@5.3.4".
warning " > @strapi/plugin-users-permissions@4.13.7" has unmet peer dependency "styled-components@5.3.3".
warning "@strapi/strapi > @strapi/plugin-content-type-builder@4.13.7" has unmet peer dependency "react@^17.0.0 || ^18.0.0".
warning "@strapi/strapi > @strapi/plugin-content-type-builder@4.13.7" has unmet peer dependency "react-dom@^17.0.0 || ^18.0.0".
warning "@strapi/strapi > @strapi/plugin-content-type-builder@4.13.7" has unmet peer dependency "react-router-dom@5.3.4".
warning "@strapi/strapi > @strapi/plugin-content-type-builder@4.13.7" has unmet peer dependency "styled-components@5.3.3".
warning "@strapi/strapi > @strapi/plugin-email@4.13.7" has unmet peer dependency "react@^17.0.0 || ^18.0.0".
warning "@strapi/strapi > @strapi/plugin-email@4.13.7" has unmet peer dependency "react-dom@^17.0.0 || ^18.0.0".
warning "@strapi/strapi > @strapi/plugin-email@4.13.7" has unmet peer dependency "react-router-dom@5.3.4".
warning "@strapi/strapi > @strapi/plugin-email@4.13.7" has unmet peer dependency "styled-components@5.3.3".
warning "@strapi/strapi > @strapi/plugin-upload@4.13.7" has unmet peer dependency "react@^17.0.0 || ^18.0.0".
warning "@strapi/strapi > @strapi/plugin-upload@4.13.7" has unmet peer dependency "react-dom@^17.0.0 || ^18.0.0".
warning "@strapi/strapi > @strapi/plugin-upload@4.13.7" has unmet peer dependency "react-router-dom@5.3.4".
warning "@strapi/strapi > @strapi/plugin-upload@4.13.7" has unmet peer dependency "styled-components@5.3.3".
warning "@strapi/strapi > @strapi/admin > styled-components > babel-plugin-styled-components > @babel/plugin-syntax-jsx@7.22.5" has unmet peer dependency "@babel/core@^7.0.0-0".
warning " > strapi-plugin-slugify@2.3.4" has unmet peer dependency "lodash@^4.17.21".
warning " > strapi-plugin-slugify@2.3.4" has unmet peer dependency "yup@^0.32.9".
[5/5] Building fresh packages...
success Saved lockfile.
success Saved 1 new dependency.
info Direct dependencies
└─ strapi-plugin-slugify@2.3.4
info All dependencies
└─ strapi-plugin-slugify@2.3.4
```

I wonder why there are so many unmet peer dependencies, cuz i just created a new Strapi project at yesterday by using customzied settings: JS, Mysql, without eslint, And only one plugin slugify has been added.

And one of weird thing is, there are no plugins.js in the config folder, actually there's even no config folder.

Please check the files to get more informations:

[strapi-plugin-slugify-2.3.4.zip](https://github.com/ComfortablyCoding/strapi-plugin-slugify/files/12756072/strapi-plugin-slugify.zip)
[strapi-plugin-slugify-2.3.5(cant run develop).zip](https://github.com/ComfortablyCoding/strapi-plugin-slugify/files/12756101/strapi-plugin-slugify-2.3.5.cant.run.develop.zip)

**Comment by GoldenCoffee** [comment]
Okay i'm kinda silly🤣, Strapi just updated to 4.14.0 with bug fixed, also in last night too:
https://github.com/strapi/strapi/releases

So i just updated my Strapi to lastest version, Warnings are gone, and it can be run now, but it still throws up error and there's no plugin.js locate config folder.

**Comment by ComfortablyCoding** [comment]
Can you share a repo with a reproducible example for the validation issue?

**Comment by GoldenCoffee** [comment]
> Can you share a repo with a reproducible example for the validation issue?
> 
> What config folder are you referring to?
> 
> P.S. Regarding this plugin not working on earlier version than 4.14.0 as mentioned in the readme only the latest version is supported. The reason for this is to many (breaking) things change for all 4.x versions to be supported.
> 
> P.P.S. The warnings about unmet peer does are not from this plugin as you can see from the DEP path in the warning.

Thanks for the reply😉
Indeed, i just update my Strapi to 4.14.0, but just as i said, without warning but ValidationError throws up still.
As we said, plugin.js should be located in config folder, but there's only one folder named server.

here's the repo: https://github.com/GoldenCoffee/Slugify-2.3.5---Strapi-4.14.0.git

**Comment by ComfortablyCoding** [comment]
The `plugins.js` file does not exist by default in the `config` folder. It needs to be created if it does not exist already. Looks like I did not mention that on this repos readme (I will do so).

P.S. Please note it is plugin**s**.js not plugin.js

**Comment by GoldenCoffee** [comment]
> Thanks!
> 
> The `plugins.js` file does not exist by default in the `config` folder. It needs to be created if it does not exist already. Looks like I did not mention that on this repos readme (I will do so).
> 
> P.S. Please note it is plugin**s**.js not plugin.js
> 
> P.P.S. Their is a plan to auto create these files by default moving forward but does not look like this will happen before v5. Ref: [strapi/strapi#17868 (comment)](https://github.com/strapi/strapi/issues/17868#issuecomment-1708765070)

Awesome, also thanks for the note! should i just follow the guide to create content such as this?
```
module.exports = ({ env }) => ({
  slugify: {
    enabled: true,
    config: {
      contentTypes: {
        film: {
          field: 'slug',
          references: 'title',
        },
      },
    },
  },
})
```
I manually create file before, actually I tried in last night. Yes, before the Strapi@4.14.0 released, I using Strapi@4.13.7as the latest version and added Slugify@2.3.4, same problems. 😥

Now I repeat the process and restart server again, but env looks declared, but its value is never read. And still, I only get ValidationError again.

![image](https://github.com/ComfortablyCoding/strapi-plugin-slugify/assets/92771703/7afc70fd-7f95-47d6-b807-2da97006c29b)

**Comment by ComfortablyCoding** [comment]
Can't say for sure but it looks to me like you have the config in the wrong place.

The path is `./config/plugins.js` where the starting point is the root of your strapi project.

Based on your project name (`tutorial-strapi-with-nextjs`) the path in your case would be `tutorial-strapi-with-nextjs/config/plugins.js`

**Comment by GoldenCoffee** [comment]
> I cannot say for sure but it looks to me like you have the plugin config in the wrong place.
> 
> The path to it should be `./config/plugins.js` where the starting point is the root of your strapi project.
> 
> Based on your project name (`tutorial-strapi-with-nextjs`) the path in your case would be `tutorial-strapi-with-nextjs/config/plugins.js`
> 
> See https://docs.strapi.io/dev-docs/configurations/plugins for further info.

Thanks, now it's actually available😄

Before this moment, I find `plugins.js` in local folders, No matching results, so i wonder where is it? And then I back to here to find a solution, I got _[this]_(https://github.com/ComfortablyCoding/strapi-plugin-slugify/issues/35#issuecomment-1061150578). I also pull this repo at yesterday try to fix up the problem, So I got a misunderstanding from an old version. Anyway I should check official Dev Docs before.

Thank you again for your patience and enthusiasm😘! This is a great opportunity to get started with Strapi and plugins, Especially for a newbie like me.

**Comment by ComfortablyCoding** [comment]
Your welcome!
