### ISSUE TITLE
Strapi 4.14.2 & GraphQL: Error Cannot read properties of undefined (reading 'admin::permission')

### ISSUE THREAD

**Issue by kevinblanco** [ComfortablyCoding/strapi-plugin-slugify#113]
After running `develop` I get the following error: 

```
info: [slugify] graphql detected, registering queries
TypeError: Cannot read properties of undefined (reading 'admin::permission')
   at /Users/kevin/Documents/strapi/node_modules/strapi-plugin-slugify/server/graphql/types.js:18:18
    at /Users/kevin/Documents/strapi/node_modules/lodash/lodash.js:4967:15
    at baseForOwn (/Users/kevin/Documents/strapi/node_modules/lodash/lodash.js:3032:24)
    at /Users/kevin/Documents/strapi/node_modules/lodash/lodash.js:4936:18
    at Function.forEach (/Users/kevin/Documents/strapi/node_modules/lodash/lodash.js:9410:14)
    at getCustomTypes (/Users/kevin/Documents/strapi/node_modules/strapi-plugin-slugify/server/graphql/types.js:17:4)
    at extension (/Users/kevin/Documents/strapi/node_modules/strapi-plugin-slugify/server/graphql/index.js:10:10)
    at resolveConfig (/Users/kevin/Documents/strapi/node_modules/@strapi/plugin-graphql/server/services/extension/extension.js:54:47)
    at /Users/kevin/Documents/strapi/node_modules/@strapi/plugin-graphql/server/services/extension/extension.js:60:11
    at Array.reduce (<anonymous>)
    at Object.generate (/Users/kevin/Documents/strapi/node_modules/@strapi/plugin-graphql/server/services/extension/extension.js:58:22)
    at buildMergedSchema (/Users/kevin/Documents/strapi/node_modules/@strapi/plugin-graphql/server/services/content-api/index.js:103:55)
    at Object.buildSchema (/Users/kevin/Documents/strapi/node_modules/@strapi/plugin-graphql/server/services/content-api/index.js:54:20)
    at Object.module.exports [as bootstrap] (/Users/kevin/Documents/strapi/node_modules/@strapi/plugin-graphql/server/bootstrap.js:38:66)
    at Object.bootstrap (/Users/kevin/Documents/strapi/node_modules/@strapi/strapi/dist/core/domain/module/index.js:42:53)
    at Object.bootstrap (/Users/kevin/Documents/strapi/node_modules/@strapi/strapi/dist/core/registries/modules.js:24:27)
```

Node: `v16.20.1` 
NPM: `8.19.4` 
Strapi: `4.14.2` 

package.json: 

```
{
  "name": "kevin-strapi",
  "private": true,
  "version": "0.1.0",
  "description": "",
  "scripts": {
    "develop": "strapi develop",
    "start": "strapi start",
    "build": "strapi build",
    "strapi": "strapi",
    "gcp-build": "strapi build"
  },
  "dependencies": {
    "@_sh/strapi-plugin-ckeditor": "^1.1.3",
    "@mui/x-date-pickers": "^5.0.20",
    "@offset-dev/strapi-calendar": "^0.0.9",
    "@retikolo/drag-drop-content-types": "^1.3.9",
    "@strapi-community/strapi-provider-upload-google-cloud-storage": "^4.10.5",
    "@strapi/plugin-graphql": "^4.14.2",
    "@strapi/plugin-i18n": "4.14.2",
    "@strapi/plugin-users-permissions": "4.14.2",
    "@strapi/strapi": "4.14.2",
    "better-sqlite3": "7.4.6",
    "pg": "^8.11.3",
    "strapi-google-auth": "^0.1.2",
    "strapi-plugin-config-sync": "^1.1.3",
    "strapi-plugin-duplicate-button": "^1.1.13",
    "strapi-plugin-import-export-entries": "^1.21.1",
    "strapi-plugin-publisher": "^1.4.1",
    "strapi-plugin-slugify": "^2.3.3"
  },
  "author": {
    "name": "Kevin Blanco"
  },
  "strapi": {
    "uuid": "852386d6-6f2a-4d8b-81d5-0dbd1e2f1b02"
  },
  "engines": {
    "node": "v16.20",
    "npm": "8.19"
  },
  "license": "MIT"
}
```

**ALREADY TRIED:**

Deleting `.cache` 
Deleting `npm_modules` 
Deleting `yarn` and `package` locks. 
Use latest `"strapi-plugin-slugify": "^2.3.5"` same issue.

**Comment by ComfortablyCoding** [comment]
This is generally due to a loading order issue with the graphql plugin and this one.

The slugify plugin must be placed before it in the `plugins.js` config file.  See https://github.com/ComfortablyCoding/strapi-plugin-slugify#additional-requirement-for-graphql

**Comment by ComfortablyCoding** [comment]
Closing due to inactivity. We can re-open if issue is still happening after steps outlined above are done.
